"$schema" = 'https://starship.rs/config-schema.json'
scan_timeout = 10

add_newline = true

[character]
success_symbol = '[âœ](bold green)'

[directory]
read_only = " ó°Œ¾"

[line_break]
disabled = false 

[git_branch]
symbol = "ï˜ "

[git_commit]
commit_hash_length = 7
format = "on [$hash]($style)"
tag_symbol = ' ï’ '

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'

[git_metrics]
disabled = false
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'

[hg_branch]
symbol = "ï˜ "

[golang]
format = 'via [Go $version](red bold) '

[nodejs]
format = 'via [NodeJS $version](bold green) '

[rust]
format = 'via [Rust $version](red bold) '

[lua]
format = 'via [Lua $version](bold blue) '

[java]
format = 'via [Java $version](red dimmed)'

[python]
format = 'via [Python $version](yellow bold) '
pyenv_version_name = true

[gradle]
format = 'via [Gradle $version](bold purple) '

[zig]
symbol = 'âš¡ï¸ Zig'

[direnv]
disabled = false

[sudo]
style = 'bold green'
symbol = 'ğŸ‘©â€ğŸ’» '
disabled = false
